//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class PropertyData
{
    public short PropertyID { get; set; }
    public string Heading { get; set; }
    public string Address { get; set; }
    public Nullable<double> PostalCode { get; set; }
    public Nullable<double> Size { get; set; }
    public Nullable<double> Price { get; set; }
    public string UserName { get; set; }
    public string Description { get; set; }
    public Nullable<double> Bedroom { get; set; }
    public Nullable<double> Bathroom { get; set; }
    public string PropertyImage { get; set; }
}
